@startuml
hide empty methods
hide empty attributes
hide circle
skinparam classAttributeIconSize 0
class ebg_comp_BG_204060254 as "ebg-comp:BG/204060254"
ebg_comp_BG_204060254 : a rov:RegisteredOrganization
class ebg_comp_BG_204060254_GUID as "ebg-comp:BG/204060254/GUID"
ebg_comp_BG_204060254 --> ebg_comp_BG_204060254_GUID : adms:identifier
class ebg_comp_BG_204060254_id as "ebg-comp:BG/204060254/id"
ebg_comp_BG_204060254 --> ebg_comp_BG_204060254_id : rov:registration
ebg_comp_BG_204060254_GUID : a adms:Identifier
class ebg_reg_BG_GUID as "ebg-reg:BG/GUID"
ebg_comp_BG_204060254_GUID --> ebg_reg_BG_GUID : dct:creator
ebg_comp_BG_204060254_GUID :  "GUID used to reach company page in register"
ebg_comp_BG_204060254_GUID : skos:notation "617f4edf8c154f4296efdf146513de21"
class ebg_reg_BG as "ebg-reg:BG"
ebg_reg_BG : a ebg:Register
ebg_reg_BG : dc:identifier "BG"
ebg_reg_BG : rov:legalName "Търговски регистър"@bg
ebg_reg_BG : schema:url <http://www.brra.bg/Default.ra>
ebg_reg_BG : skos:prefLabel "BG Commercial Register"@en
ebg_reg_BG_GUID : a ebg:Register
ebg_reg_BG_GUID --> ebg_reg_BG : dct:isPartOf
ebg_reg_BG_GUID : dc:identifier "BG/GUID"
ebg_reg_BG_GUID : ebg:urlTemplate "https://public.brra.bg/CheckUps/Verifications/ActiveCondition.ra?guid={}"
ebg_reg_BG_GUID : rdfs:comment "Use to reach the official register page of a company"
ebg_reg_BG_GUID : rov:legalName "Търговски регистър - GUID"@bg
ebg_reg_BG_GUID : skos:prefLabel "BG Commercial Register - GUID"@en
ebg_comp_BG_204060254_id : a adms:Identifier
ebg_comp_BG_204060254_id --> ebg_reg_BG : dct:creator
ebg_comp_BG_204060254_id :  "Official ID"
ebg_comp_BG_204060254_id : skos:notation "204060254"
@enduml
